### ISSUE TITLE
`Database file is in use` error while running Subspace desktop in development

### ISSUE THREAD

**Issue by isSerge** [subspace/subspace-desktop#241]
I am running Subspace desktop v0.6.0 in development in the background. After approximately 30-60 minutes I get the following error:
```
Version: 0.6.0-d01c35f5a65

   0: backtrace::backtrace::libunwind::trace
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/backtrace/mod.rs:66:5
      backtrace::backtrace::trace
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/backtrace/mod.rs:53:14
   1: backtrace::capture::Backtrace::create
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/capture.rs:176:9
      backtrace::capture::Backtrace::new
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.64/src/capture.rs:140:22
   2: sp_panic_handler::panic_hook
             at /Users/apple/.cargo/git/checkouts/substrate-7bc20b373ca3e834/24bea4c/primitives/panic-handler/src/lib.rs:166:18
      sp_panic_handler::set::{{closure}}
             at /Users/apple/.cargo/git/checkouts/substrate-7bc20b373ca3e834/24bea4c/primitives/panic-handler/src/lib.rs:62:12
   3: std::panicking::rust_panic_with_hook
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panicking.rs:702:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panicking.rs:588:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/sys_common/backtrace.rs:138:18
   6: rust_begin_unwind
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panicking.rs:584:5
   7: core::panicking::panic_fmt
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/panicking.rs:143:14
   8: core::result::unwrap_failed
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/result.rs:1749:5
   9: core::result::Result<T,E>::unwrap
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/result.rs:1065:23
      subspace_desktop::node::start_node::{{closure}}
             at src/node.rs:54:5
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/future/mod.rs:84:19
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/map.rs:55:37
  11: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/lib.rs:91:13
      subspace_desktop::main::{{closure}}::{{closure}}::{{closure}}
             at src/node.rs:52:1
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/future/mod.rs:84:19
      tauri::hooks::InvokeResolver<R>::respond_async_serialized::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.11/src/hooks.rs:196:44
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/future/mod.rs:84:19
  12: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
      tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
      tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panic.rs:137:14
      tokio::runtime::task::harness::poll_future
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  13: tokio::runtime::task::raw::RawTask::poll
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
      tokio::runtime::task::LocalNotified<S>::run
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:376:9
      tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:431:13
      tokio::coop::with_budget::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
      std::thread::local::LocalKey<T>::try_with
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/thread/local.rs:413:16
      std::thread::local::LocalKey<T>::with
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/thread/local.rs:389:9
  14: tokio::coop::with_budget
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
      tokio::coop::budget
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
      tokio::runtime::thread_pool::worker::Context::run_task
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:430:9
  15: tokio::runtime::thread_pool::worker::Context::run
  16: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:382:17
      tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/scoped_tls.rs:61:9
  17: tokio::runtime::thread_pool::worker::run
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:379:5
  18: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:358:45
      <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/task.rs:42:21
  19: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
      tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
      tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panic.rs:137:14
      tokio::runtime::task::harness::poll_future
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  20: tokio::runtime::task::raw::RawTask::poll
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
      tokio::runtime::task::UnownedTask<S>::run
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:413:9
      tokio::runtime::blocking::pool::Task::run
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:91:9
      tokio::runtime::blocking::pool::Inner::run
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:325:17
  21: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:300:13
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/sys_common/backtrace.rs:122:18
  22: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/thread/mod.rs:498:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/thread/mod.rs:497:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/core/src/ops/function.rs:227:5
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/c5c610aad0a012a9228ecb83cc19e77111a52140/library/std/src/sys/unix/thread.rs:108:17
  24: _pthread_jit_write_protect_np


Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Backend error: Database file is in use. (Resource temporarily unavailable (os error 35))', src/node.rs:54

This is a bug. Please report it at:

        https://discord.gg/vhKF9w3x

```

Reproduced multiple times

**Comment by ozgunozerk** [comment]
Unable to produce on my end, 3 days of trial, never happened... Is it still happening on your side @isSerge ?
